services:
  accounts:
    image: "dangphat1412/accounts:latest"
    container_name: accounts-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking-ms
  loans:
    image: "dangphat1412/loans:latest"
    container_name: loans-service
    ports:
      - "8091:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banking-ms
  cards:
    image: "dangphat1412/cards:latest"
    container_name: cards-service
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
networks:
  banking-ms:
    driver: "bridge"

