spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:${config.host}"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
config:
  host: "http://localhost:8071"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
info:
  app:
    name: "Gateway Server"
    description: "This service routes requests to appropriate microservices."
    version: "1.0.0"
logging:
  level:
    com:
      secure:
        gatewayserver: DEBUG