spring:
  config:
    activate:
      on-profile: prod
build:
  version: 3.0.0
accounts:
  message: "Welcome to the Accounts Service PROD"
  contactDetails:
    name: "Support Team PROD"
    email: "spprod@gmail.com"
  onCallSupport:
    - (1234) 567-8901
    - (9876) 543-2109