spring:
  config:
    activate:
      on-profile: qa
build:
  version: 2.0.0
accounts:
  message: "Welcome to the Accounts Service QA"
  contactDetails:
    name: "Support Team QA"
    email: "spqa@gmail.com"
  onCallSupport:
    - (1234) 567-8901
    - (9876) 543-2109